### PR TITLE
Add 'Zfhmin' extension

### PR DESCRIPTION
**Pull request by a4lg**
'Zfhmin' is a subset of 'Zfh' extension (which is implemented in Spike).
Because 'Zfhmin' is ratified along with 'Zfh', it should be good to implement this extension in Spike.

### CODE REVIEW

**Comment by a4lg** [comment]
It seems it conflicts with #831 (larger PR that is going to implement Zfinx/Zdinx/Zhinx/Zhinxmin), which implements a part of 'Zfhmin' in the process.

If 'Zfinx' PR (#831) is going to be merged soon, I'm happy to work on it (to make another PR).
If not, merging this PR would be a quicker solution to add an extension to Spike's "implemented ratified extensions" list.

### EDIT
#831 does not implement all 'Zfhmin' instructions. So, we have to change following instructions for full 'Zfhmin' support based on 'Zfinx' work (if we choose not to merge this PR):
*  FLH / FSH
*  FMV.X.H / FMV.H.X
*  FCVT.Q.H / FCVT.H.Q

**Comment by a4lg** [comment]
I changed the pull request to imply `EXT_ZFHMIN` by 'Zfh'. That would make conflict with #831 smaller.

**Comment by aswaterman** [comment]
I support merging this PR as-is, then rebasing the bigger PR on top of it.

The code looks good to me!
